### ISSUE TITLE
Session-Handling SessionIDs not following PTP standard?

### ISSUE THREAD

**Issue by volkerjaenisch** [Parrot-Developers/sequoia-ptpy#10]
Hi!
Is there a discussion forum? Do not like to post an issue report each time I have a suggestion.

I have a strange problem with Canon DSLRs and gphoto2 as well as with PTPy. After some shots the device does not react anymore. Gphoto is very complex and not easy to debug. With PTPy I am able to reproduce and debug this behavior and it seems to be dangling sessions.

To reproduce :
```
with camera.session():

    # The open session and close sessions operations are called
    # in the background as needed.
    print(camera.get_device_info())
    # Allow remote shutter release.
    print( camera.eos_set_remote_mode(1))
    # Actual shutter release
    print( camera.eos_remote_release())
    <Terminate process here: kill -9>

```
This leads to a dangling session (ID=2). Rerunning the code yields only SessionNotOpen messages and capturing is no longer possible. Manual rebooting of the camera seems the only cure ---
BUT if you insert a second camera.open_session() in front of the capture command you will get a session ID=3 that allows for capturing.
This weird behavior found me to have a closer look at your session code and the PTP Spezifikation.

```
    def open_session(self):
        self.__session += 1
        self.__transaction = 1
        ptp = Container(
            OperationCode='OpenSession',
            # Only the OpenSession operation is allowed to have a 0
            # SessionID, because no session is open yet.
            SessionID=0,
            TransactionID=0,
            Parameter=[self.__session]
        )
        response = self.mesg(ptp)
        if response.ResponseCode == 'OK':
            self.__session_open = True
        return response
```

The comment stated that the first call to OpenSession should be performed with a session ID of zero but the Spezification reads the opposite:

```
PIMA 15740: 2000  
9.2.1 SessionID 
Each session shall have a SessionID that consists of one device-unique 32-bit unsigned 
integer (UINT32).  SessionIDs are assigned by the Initiator as a parameter to the 
OpenSession operation, and must be non-zero. 
```

I suppose that the philosophy behind the PTP SessionIDs is comparable to the one in e.g. IMAP.
Therefore I changed the code a bit

```
    def open_session(self, session_id = None):
        self.__session += 1
        self.__transaction = 1
        ptp = Container(
            OperationCode='OpenSession',
            # Only the OpenSession operation is allowed to have a 0
            # SessionID, because no session is open yet.
            SessionID= session_id or self.__session,
            TransactionID=0,
            Parameter=[self.__session]
        )
        response = self.mesg(ptp)
        if response.ResponseCode == 'OK':
            self.__session_open = True
        else:
            print('error opening session', response)
        return response

    def close_session(self, session_id = None):
        ptp = Container(
            OperationCode='CloseSession',
            SessionID= session_id or self.__session,
            TransactionID=self.__transaction,
            Parameter=[]
        )
        response = self.mesg(ptp)
        if response.ResponseCode == 'OK':
            self.__session_open = False
        return response
```

The additional session_id parameter are for testing purpose, only. **Utilizing this code the procedure with interrupting the code before close_session is called does no longer stall the camera.**
This is for sure a particular finding only true for my system and a canon 6D.

I also suggest to capsulize the sessions in a session class. Without isolating the sessions from each other there is no way to keep track of them. At the moment the sessionIDs are simply incremented. This works as long as the user does only uses really atomistic operations. But if a user needs long running tasks this will lead to problems sooner or later.

**Comment by volkerjaenisch** [comment]
BTW. I am working currently on a high level API for exposing the file-system of the camera in terms of paths and folders. This is work in progress but I like to contribute this code to ptpy.

**Comment by domenzain** [comment]
I've created a gitter.im community at [gitter.im/python-ptpy](http://gitter.im/python-ptpy) . I think it will be more flexible than Github for this type of discussion and quick exchange.

**Comment by domenzain** [comment]
As for SessionID in `ISO15740:2013(E) 9.3.3`, or `PIMA15740:2000 9.3.2`:

> **SessionID**: The identifier for the session within which this operation is being initiated.  This value is assigned by the Initiator using the OpenSession operation.  This field should be set to 0x00000000 for operations that do not occur within a session, and for the OpenSession OperationRequest dataset.  Refer to Clause 9.2.1 for a description of SessionIDs.

The text you cited still applies. But to the first parameter of the `OpenSession` operation request (always non-zero), not the `SessionID` itself (_should_ be zero).

Another transport detail is that over USB the `SessionID` is implicit. Even though the field is specified by the standard it isn't actually sent over USB in any place other than the `OpenSession` request parameter (for example, try setting the parameter to 1 permanently).

As for the stalling, I think that's related to the EOS events not being polled. There should be a regular polling (though not too often, as that can cause stalls as well...) I suggest around 200 ms. If all you want to do is trigger, you can simply throw away the events.

I will get around to automatic polling of EOS events soon. I'm thinking whether I should mix them with regular PTP events or not...

**Comment by volkerjaenisch** [comment]
Thanks for clarification!
But  I still do not understand why the modified code is robust against interruptions and the unmodified code not?

**Comment by domenzain** [comment]
If you're using the modified code as show above, you should see no change in behaviour at all, other than a few extra output lines telling you that the `OpenSession` request returns a `ResponseCode` of `SessionAlreadyOpen` (or something other than `OK`).

Over USB, the SessionID is merely a specification formality. If the camera has at least one unclosed session, it will keep responding to any PTP request that comes its way as there is no way for the camera to tell which requests correspond to which session. Some cameras will even respond if no session was ever opened...

A `kill -9` (best avoid that) terminates the Python interpreter before before the USB interface is released. So relaunching that script is exactly as if the initial interaction never ended from the camera's perspective.

I think the stalls are unrelated to the opened session. And more probably relate to the EOS events accumulating without being polled. I've made a few modifications in 447583af1ad1f5250ace23498d7da40a7b4faadf to be able to poll these in a thread-safe manner.

**Comment by domenzain** [comment]
I'm closing this, as it seems the stalls were in fact unrelated to the sessions themselves (and these are compliant).
