### ISSUE TITLE
Can not turn Wifi ON

### ISSUE THREAD

**Issue by kolins-cz** [Parrot-Developers/sequoia-ptpy#11]
I am trying to turn wifi on sequoia ON and OFF with following code:

#!/usr/bin/env python
import ptpy

camera = ptpy.PTPy()
with camera.session():
    status = camera.set_device_prop_value('WifiStatus', 'ON')
    print(status);

Response is:

Container:
    TransactionID = 1
    SessionID = 1
    ResponseCode = InvalidDevicePropValue
    Parameter = ListContainer:

I suspect problem is in unicode something. If get 'WifiStatus' it returns [u'ON',.......
When I run trigger.py, sequoia takes pictures, so i think my environment is set up correctly.

**Comment by domenzain** [comment]
That error code means the camera does not support the operation you're trying.
To find out whether a camera supports a property, do this:
```python
from ptpy import PTPy
c = PTPy()
with c.session():
    # Is the property supported?
    prop = 'WifiStatus'
    info = c.get_device_info()
    print(
        'Good to go!'
        if prop in info.DevicePropertiesSupported
        else 'Not supported...'
    )
```
Unless it is a highly non-compliant camera, it will never accept a property which isn't in that list. Nor will it ever complain that a property in the list is an `InvalidDevicePropValue`.

For Sequoia you might want to get the [latest firmware](https://community.parrot.com/t5/Sequoia/bd-p/Sequoia).
