### ISSUE TITLE
Examples are too basic

### ISSUE THREAD

**Issue by rarmstrong22** [Parrot-Developers/sequoia-ptpy#13]
Hello,

I realize that this is more of a "feature request" than an issue: it'd be great if we had some more advanced examples that showed things like 
- Listing/downloading/deleting contents of storage.
- Live view.

Thanks for writing and sharing this library, by the way.
Rick

**Comment by domenzain** [comment]
If you've got other example requests list them here.
I'll try to give canonical implementations within a couple of weeks.

**Comment by domenzain** [comment]
Hi @rarmstrong22, please have a look at `download_all_images.py`.
The only difference with live view is downloading the images in ObjectAdded events.

**Comment by domenzain** [comment]
There is now a more involved example with many cameras simultaneously acquiring and downloading images.

Please see `examples/all_cameras_live.py`

**Comment by rarmstrong22** [comment]
Thanks! We're into a different part of our project at the moment, but I'll try out the new examples next time we revisit the sequoia.
