### ISSUE TITLE
Support for IP transport layer

### ISSUE THREAD

**Issue by greg-draganfly** [Parrot-Developers/sequoia-ptpy#2]
I would like to see support for an IP transport.  Some platforms have issues in the USB layer so removing dependency on pyusb would be great.

**Comment by domenzain** [comment]
This is planned as mentioned in `README.md`.
It will be incorporated into the next tagged release.

**Comment by domenzain** [comment]
As of  4679744ce1aa04b8eef44df17f1327d05de4c88f, the IP transport should be useable.

There isn't yet any automatic discovery, but it can be instantiated as:
```python
from ptpy.transports.ip import IPTransport
from ptpy import PTPy

c = PTPy(transport=IPTransport, device='192.168.47.1')
```
