### ISSUE TITLE
Can't import "Range" from construct 2.8.22 package into usb.py

### ISSUE THREAD

**Issue by jacklia** [Parrot-Developers/sequoia-ptpy#24]
Issue is described here: https://stackoverflow.com/questions/50605894/python-windows-7-importerror-cannot-import-name-x

where the file "USB transport.py" is the same as usb.py

**Comment by domenzain** [comment]
Hi @jacklia , I stopped following `construct` head because of changes that break essential functionality of PTPy and drop of support in `Embedded` `Switch`es.
The general unstable API described as part of the transition to 2.9 actually started earlier...
It was an uphill battle with the maintainer to unbreak things.

The latest "known good" is 2.8.8 and this is reflected in `requirements.txt`.
If you know what you need maybe I can give you a hand.

**Comment by jacklia** [comment]
Hi @domenzain , thanks for the help. I downloaded construct 2.8.8 and that problem is now resolved. However when trying to run `camera=PTPy()`, I'm running into a new error: `USBError: [Errno 2] Entity not found` using pyusb 1.0.0rc1. I know that my computer recognizes my camera so I'm not sure why this is the case.

**Comment by domenzain** [comment]
Could you
```bash
export PYUSB_DEBUG=debug
export PTPY_DEBUG=1
python your_script.py > diagnostic.log 2>&1
```
and share the log?

**Comment by jacklia** [comment]
I'm getting "'export' is not recognized as an internal or external command, operable program or batch file"? Sorry if I'm misinterpreting what you mean, I'm not very experienced. I'm running Anaconda/Spyder on Windows 10 if that helps.

**Comment by jacklia** [comment]
I'm not sure if this is what is needed but here is the Traceback:
```
Traceback (most recent call last):

  File "<ipython-input-27-3f88a9a17fe2>", line 1, in <module>
    runfile('F:/camera.py', wdir='F:')

  File "C:/Users/Geoffrey/Anaconda3/lib/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:/Users/Geoffrey/Anaconda3/lib/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/camera.py", line 56, in <module>
    camera = PTPy()

  File "F:\PTPy.py", line 119, in __new__
    plain_camera = plain(device=device)

  File "F:\PTP.py", line 720, in __init__
    super(PTP, self).__init__(*args, **kwargs)

  File "F:\USBtransport.py", line 105, in __init__
    self.__acquire_camera(devs)

  File "F:\USBtransport.py", line 138, in __acquire_camera
    for _ in self.__available_cameras(devs):

  File "F:\USBtransport.py", line 126, in __available_cameras
    for dev in devs:

  File "F:\pyusb-1.0.0rc1\pyusb-1.0.0rc1\usb\core.py", line 1249, in device_iter
    if _interop._all(tests) and (custom_match is None or custom_match(d)):

  File "F:\USBtransport.py", line 60, in __call__
    for cfg in device:

  File "F:\pyusb-1.0.0rc1\pyusb-1.0.0rc1\usb\core.py", line 1094, in __iter__
    yield Configuration(self, i)

  File "F:\pyusb-1.0.0rc1\pyusb-1.0.0rc1\usb\core.py", line 586, in __init__
    configuration

  File "F:\pyusb-1.0.0rc1\pyusb-1.0.0rc1\usb\backend\libusb1.py", line 757, in get_configuration_descriptor
    config, byref(cfg)))

  File "F:\pyusb-1.0.0rc1\pyusb-1.0.0rc1\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

USBError: [Errno 2] Entity not found
```

**Comment by jacklia** [comment]
Here is the log file for the main file I am using that contains `camera=PTPy()`:
```
DEBUG:root:DEBUG
DEBUG:PTP:Init PTP
DEBUG:USBtransport:Init USB
DEBUG:PTP:Set PTP endianness
DEBUG:USBtransport:No device provided, probing all USB devices.
```

(My camera is definitely connected).

For both PTP and PTPy I just get this:
```
DEBUG:root:DEBUG
DEBUG:root:DEBUG
```

**Comment by domenzain** [comment]
Hi @jacklia,

It looks like an issue with libusb drivers under Windows. Have you installed those?

I recommend https://zadig.akeo.ie/ to install the libusb driver for your particular USB VendorID and ProductID.

**Comment by jacklia** [comment]
Hi @domenzain,

Thanks for the help. I actually switched over to Ubuntu/Linux and I no longer have this problem. It does appear to be a Windows issue and I'm not sure how to resolve it. I had installed the driver through zadig and it still didn't work.

**Comment by domenzain** [comment]
Sadly there is no easy way of having the latest libusb drivers on Windows, you really need to know which is your device and make sure the libusb drivers take precedence...

I will close this, as it seems unrelated to PTPy itself.
