### ISSUE TITLE
Error in usb.py event function

### ISSUE THREAD

**Issue by rejogc** [Parrot-Developers/sequoia-ptpy#25]
The event function in usb.py has the option to be called with a wait parameter. When set to True the event function should wait for and event to be queued if there's no event in the event queue. Unfortunately the event function does not respond appropriately when the wait parameter is set to True. It just goes it's merry way.  Here is the function:

```python
def event(self, wait=False):
        '''Check event.
        If `wait` this function is blocking. Otherwise it may return None.
        '''
        evt = None
        usbdata = None
        if not self.__event_queue.empty():
            usbdata = self.__event_queue.get(block=not wait)
        if usbdata is not None:
            evt = self.__parse_response(usbdata)
        return evt
```
The line 'usbdata = self.__event_queue.get(block=not wait)' will never execute if the queue is empty so it will never a blocking get. A better approach is this:

        if wait:
            usbdata = self.__event_queue.get(block=True)
        elif not self.__event_queue.empty():
            usbdata = self.__event_queue.get(block=False)

**Comment by domenzain** [comment]
Thank you @rejogc.
As of 722154a, this is now the case.
