### ISSUE TITLE
Python 3 incompatibility in event polling

### ISSUE THREAD

**Issue by SteveStrop** [Parrot-Developers/sequoia-ptpy#27]
I'm new to github and ptpy. Apologies if anything posted here is not in the correct format.

I'm trying to access my Nikon D800 camera using ptpy. I've installed a libusb-win32 driver (for the camera) and am running the example script from here under Python 3.

This is the output from the example script:

[ptpy error report.txt](https://github.com/Parrot-Developers/sequoia-ptpy/files/2164012/ptpy.error.report.txt)

Please note I've added a print(i,device) around line 75 to the example script to see what info I'm getting from my camera. 

I emailed Luis Domenzain and he suggested 
"This looks like a PTPy bug under Python 3.
Please post an issue to GitHub for follow-up."

So that's what I'm doing :)

Thanks very much for any help you can give me on this one.

Steve C

PS I have tried other driver options from Zadig but I get similar errors in a seemingly infinite loop. This is the only driver option  that (finally) exits with a code 0

Driver details:

 ![driver_screen_shot](https://user-images.githubusercontent.com/40737998/42289886-23ce2dc6-7fba-11e8-8984-293b34439ab6.jpg)

**Comment by domenzain** [comment]
Hi Steve,

Could you give it a go with the latest master?
This looks like a simple bug under Python3 with an incorrect comparison between a string and a bytes buffer.

Best,

**Comment by SteveStrop** [comment]
Thanks that works great!
