### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by AlexisPotvin** [Parrot-Developers/sequoia-ptpy#5]
Is there any package installation other then pip install . or python setup.py install?
Because i keep having Import Error for package 
LengthValueAdapter
BitField

**Comment by domenzain** [comment]
Those have disappeared in the latest Construct with a rethought API.
I think it's best to adapt to that.

In the meantime you can change the `requirements.txt` line for construct to `construct==2.5.2` or `construct<2.5.5`.

**Comment by domenzain** [comment]
#7 is a duplicate of this same bug.

**Comment by domenzain** [comment]
This is resolved with the migration.

**Comment by jcea** [comment]
Hitting this. We need a new PYPI release :-)
